# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20160917_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrocoAccount',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('mt4_id', models.IntegerField()),
                ('group', models.CharField(max_length=50)),
                ('creation_ts', models.DateTimeField()),
                ('user', models.ForeignKey(related_name='accounts', to='crm.BrocoUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='brocomt4account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_fa',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_fr',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_hy',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_ka',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_pl',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_pt',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_th',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_uk',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='address_zh_cn',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_ar',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_en',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_fa',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_fr',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_hy',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_id',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_ka',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_pl',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_pt',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_ru',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_th',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_uk',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='caption_zh_cn',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_ar',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_en',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_fa',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_fr',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_hy',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_id',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_ka',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_pl',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_pt',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_ru',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_th',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_uk',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='metro_zh_cn',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_fa',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_hy',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_id',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_th',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='regionaloffice',
            name='name_zh_cn',
        ),
        migrations.DeleteModel(
            name='BrocoMt4Account',
        ),
    ]
